collections:
  java:
    output: true
# <name>:
#   output: true

defaults:
  - scope:
      type: "java"
    values:
      layout: "article"
# - scope:
#     type: "<name>"
#   values:
#     layout: "article"

highlighter: rouge

url: "https://lg-ks-programmierag.github.io"
baseurl: ""