collections:
  java:
    output: true
    #order:
    #  - einführung.md

defaults:
  - scope:
      type: "java"
    values:
      layout: "article"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"



url: "https://lg-ks-programmierag.github.io"
baseurl: ""